image: maven:3.8.4-openjdk-17

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building and testing project"
    - mvn package

sonarcloud-check:
  image: maven:3-openjdk-17
  stage: test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=fit-and-fun-group_fit-and-fun
  only:
    - merge_requests
    - main
    - develop
