services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  camunda:
    image: 'camunda/camunda-bpm-platform:7.20.0'
    ports:
      - '5433:8080'
    volumes:
      - './target/fit-and-fun-0.0.1-SNAPSHOT.jar:/camunda/camunda/webapps/fit-and-fun-0.0.1-SNAPSHOT.jar'
    restart: unless-stopped