version: 2.0.3

services:
  postgres:
    container_name: faf-postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=faf_db'
      - 'POSTGRES_PASSWORD=faf_secret'
      - 'POSTGRES_USER=faf_user'
    ports:
      - '5434:5432'
  pgadmin:
    container_name: faf-pgadmin
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - '5050:80'
